apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-service
  namespace: metal
  labels:
    app: k8s-demo-app
spec:
  selector:
    app: k8s-demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
